import axios from 'axios';
import Head from 'next/head';
import Link from 'next/link';

function Home({ currentUser }) {
  console.log('i am on the client ', currentUser);

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="navbar navbar-expand-lg navbar-dark bg-primary mb-2">
        <div className="container">
          <a className="navbar-brand" href="#">Navbar</a>
          <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span className="navbar-toggler-icon"></span>
          </button>
          <div className="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div className="navbar-nav">
              <a className="nav-item nav-link active" href="#">Home <span className="sr-only">(current)</span></a>
              <Link href="/auth/signup">
              <a className="nav-item nav-link" >Login</a>
              </Link>
              <a className="nav-item nav-link" href="#">Pricing</a>
               {
                 currentUser &&
              <a className="nav-item nav-link" href="#">Logout</a>
               }
            </div>
          </div>
        </div>
      </nav>

      <div className="container">
      <h1>Landing page</h1>
      </div>
    </div>
  )
}

Home.getInitialProps = async (ctx) => {
  try {
    axios.defaults.withCredentials = true;
    const res = await axios.get('http://localhost:3000/api/users/currentuser', ctx.req ? {
      headers: {
        'content-type': 'application/json',
        cookie: ctx.req.headers.cookie || null
      }
    } : { });

    console.log(res.data);
    return res.data;
  } catch (error) {
    return error.response.data ;
  }

}

export default Home;