import Head from 'next/head';

function Home({ currentUser }) {
  return (
    < >
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container">
      <h1>Landing page</h1>
      
      </div>
    </>
  )
}

export default Home;