import Head from 'next/head';
import Router from 'next/router';
import React, { useState } from 'react';
import useRequest from '../../hooks/use-request';

export default function Signin() {
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [loading, setLoading] = useState(false);
    const { doRequest, errors } = useRequest({
        url: 'http://localhost:3000/api/users/signin',
        method: 'post',
        body: {
            email, password
        },
        onSuccess: () => Router.push('/')
    });

    const handleSubmit = async (e) => {
        e.preventDefault();
        setLoading(true);

        await doRequest();
        setLoading(false);
    }

    return (
        <>
            <Head>
                <title>Sign In</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <form onSubmit={handleSubmit} className="container mt-5">
                <h1>Sign In</h1>
                <div className="form-group mt-3">
                    <label>Email Address</label>
                    <input required value={email} onChange={e => setEmail(e.target.value)} className="form-control" />
                </div>
                <div className="form-group mt-3">
                    <label>Password</label>
                    <input value={password} onChange={e => setPassword(e.target.value)} type="password" required className="form-control" />
                </div>
                {
                    errors 
                }
                <button className="btn btn-primary mt-3">
                    {
                        loading ?
                            <div className="spinner-grow text-light" role="status">
                                <span className="sr-only"></span>
                            </div> : <span>Sign In</span>
                    }
                </button>
            </form>
        </>
    )
}
