http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api-users:
    host: localhost
    paths: '/api/users/*'
  api-tickets:
    host: localhost
    paths: ['/api/tickets/*','/api/tickets'] 
serviceEndpoints:
  users:
    url: 'http://localhost:3000'
  tickets:
    url: 'http://localhost:3001'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api-users
    policies:
      - proxy:
          - action:
              serviceEndpoint: users 
              changeOrigin: true
  pipelines-tickets:
    apiEndpoints:
      - api-tickets
    policies:
      - proxy:
          - action:
              serviceEndpoint: tickets 
              changeOrigin: true
